[package]
name = "my-jam-service"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
jam-pvm-common = { version = "0.1.26", default-features = false, features = ["service"] }
polkavm-derive = "0.29"

[profile.release]
panic = "abort"
lto = true
opt-level = 'z'